In [1]:
import numpy as np

In [12]:
C_names = np.array("Barnes Abramson Macduff Johnson Andrews Lewin Brown".split())
C_names

array(['Barnes', 'Abramson', 'Macduff', 'Johnson', 'Andrews', 'Lewin',
       'Brown'], dtype='<U8')

In [26]:
#1. Сгенерировать NumPy массив (“Customer’s roaming call duration”),
#содержащий эту информацию, используя подходящий метод модуля random.
C_duration = np.random.randint(100,350,(7,6))
C_duration

array([[337, 263, 174, 296, 195, 224],
       [346, 126, 247, 125, 337, 177],
       [267, 232, 167, 176, 250, 252],
       [145, 246, 120, 211, 186, 257],
       [307, 334, 120, 210, 102, 263],
       [342, 178, 152, 163, 184, 234],
       [323, 107, 175, 249, 164, 221]])

In [27]:
#2. Выбрать из него (вывести) все строки, содержащие информацию о
#клиентах Abramson и Johnson.
C_duration[(C_names == 'Abramson') | (C_names == 'Johnson')]

array([[346, 126, 247, 125, 337, 177],
       [145, 246, 120, 211, 186, 257]])

In [28]:
#3. Выбрать информацию обо всех клиентах, кроме Macduff и Lewin
C_duration[(C_names != 'Macduff') & (C_names != 'Lewin')]

array([[337, 263, 174, 296, 195, 224],
       [346, 126, 247, 125, 337, 177],
       [145, 246, 120, 211, 186, 257],
       [307, 334, 120, 210, 102, 263],
       [323, 107, 175, 249, 164, 221]])

In [29]:
#4. Вывести информацию о клиенте Brown за период 2-4 месяцы
C_duration[C_names == 'Brown', 1:4] 

array([[107, 175, 249]])

In [30]:
#5. Вывести информацию обо всех клиентах, кроме Barnes за нечетные
#месяцы.
C_duration[C_names != 'Barnes', 0::2]

array([[346, 247, 337],
       [267, 167, 250],
       [145, 120, 186],
       [307, 120, 102],
       [342, 152, 184],
       [323, 175, 164]])

In [31]:
#6. Стоимость минуты разговора в роуминге составляет 1.6$. Создайте
#новый массив NumPy (Customer’s roaming call cost), содержащий информацию
#о расходах каждого клиента в определенный месяц (основываясь на данных
#из массива “Customer’s roaming call duration”).
price = 1.6
C_cost = price * C_duration
C_cost

array([[539.2, 420.8, 278.4, 473.6, 312. , 358.4],
       [553.6, 201.6, 395.2, 200. , 539.2, 283.2],
       [427.2, 371.2, 267.2, 281.6, 400. , 403.2],
       [232. , 393.6, 192. , 337.6, 297.6, 411.2],
       [491.2, 534.4, 192. , 336. , 163.2, 420.8],
       [547.2, 284.8, 243.2, 260.8, 294.4, 374.4],
       [516.8, 171.2, 280. , 398.4, 262.4, 353.6]])

In [33]:
#7. Курс доллара составляет 28 ₴. Рассчитайте и выведите общие затраты
#клиента Andrews в гривнах.
usd_uah = 28
C_cost[C_names == 'Andrews'] * usd_uah

array([[13753.6, 14963.2,  5376. ,  9408. ,  4569.6, 11782.4]])