In [1]:
import numpy as np

In [2]:
# варіант №12   К-сть міст = 12    Діапазон місяців = 5-12     Регіон 1 = Полтава     Регіон 2 = Одеса

In [3]:
# Одеса діапазон дзвінків = 100-250

In [4]:
# Полтава діапазон дзвінків = 100 - 180

In [41]:
# Перший регіон. 
# Кожна строчка даних по першому регіону відповідає місту регіону 
# (для парних варіантів). Кожен стовбець даних по першому регіону відповідає місяцю 2018 року (в
# діапазоні по варіанту, для парних варіантів)

CitiesCount = 12
MonthCount = 8
pMin = 100
pMax = 180
PoltavaRegion = np.random.randint(pMin, pMax, size = [CitiesCount, MonthCount], dtype = int)
PoltavaRegion

array([[122, 105, 165, 129, 137, 118, 155, 162],
       [147, 113, 100, 166, 178, 126, 116, 115],
       [136, 135, 151, 150, 166, 151, 157, 154],
       [107, 172, 171, 176, 179, 120, 115, 163],
       [101, 134, 110, 120, 132, 107, 145, 147],
       [160, 158, 112, 148, 139, 113, 168, 155],
       [132, 125, 174, 105, 134, 142, 172, 122],
       [119, 176, 177, 129, 168, 140, 105, 115],
       [178, 176, 143, 179, 110, 165, 121, 118],
       [120, 119, 153, 101, 143, 154, 138, 132],
       [152, 172, 140, 177, 179, 125, 133, 144],
       [136, 160, 174, 159, 116, 152, 153, 133]])

In [9]:
# Другий регіон.
# Кожна строчка даних по першому регіону відповідає місяцю 2018 року (10
# місяців) для парних варіантів
# Кожен стовбець даних по другому регіону відповідає кількості міст регіону
# (по варіанту, для парних варіантів) + 20
MounthCount = 10
CitiesCount = CitiesCount + 20
oMin = 100
oMax = 250
OdesaRegion = np.random.randint(oMin, oMax, size = [MounthCount, CitiesCount], dtype = int)
OdesaRegion

array([[121, 203, 235, 103, 157, 220, 238, 195, 192, 109, 226, 182, 196,
        134, 124, 193, 202, 238, 106, 157, 108, 183, 210, 211, 133, 115,
        192, 212, 201, 186, 208, 172],
       [194, 174, 174, 167, 122, 203, 247, 173, 137, 125, 230, 142, 106,
        141, 162, 173, 117, 220, 166, 154, 180, 237, 131, 108, 152, 115,
        244, 222, 208, 215, 219, 191],
       [229, 200, 172, 176, 118, 242, 243, 214, 233, 233, 229, 156, 200,
        217, 248, 206, 229, 237, 105, 184, 108, 203, 181, 169, 187, 168,
        114, 111, 218, 150, 150, 225],
       [216, 106, 185, 133, 173, 148, 200, 235, 109, 180, 230, 204, 112,
        211, 130, 158, 117, 240, 139, 229, 117, 121, 151, 170, 232, 146,
        201, 190, 139, 177, 165, 183],
       [136, 192, 115, 176, 179, 216, 229, 180, 194, 150, 101, 150, 154,
        131, 190, 141, 210, 171, 170, 117, 156, 174, 112, 190, 182, 217,
        106, 119, 200, 192, 183, 247],
       [121, 196, 208, 243, 221, 226, 162, 178, 163, 198, 131, 109, 183,
  

In [48]:
# 1. Згенерувати два ndarray (матриці) по заданим регіонам, відповідно заданої
# у описі предметної області структурі та відповідної розмірності. Комірки
# матриць зберігають тривалості дзвінків абонентів у роумінгу (згенерувати
# значення в зазначеному діапазоні згідно назвам регіонів в таблиці Б.2).

# 2. Створити новий (загальний) ndarray для зберігання всієї інформації з двох
# заданих регіонів за вказаний в таблиці Б.3 діапазон місяців, виконавши
# операції зрізу, трансформації (рядки нової матриці - міста, стовпці - місяці)
# і операції об'єднання.
# Місяці по варіанту = 6-9

AllRegions = np.vstack((PoltavaRegion[:,1:5],np.transpose(OdesaRegion)[:,5:9]))
AllRegions

array([[105, 165, 129, 137],
       [113, 100, 166, 178],
       [135, 151, 150, 166],
       [172, 171, 176, 179],
       [134, 110, 120, 132],
       [158, 112, 148, 139],
       [125, 174, 105, 134],
       [176, 177, 129, 168],
       [176, 143, 179, 110],
       [119, 153, 101, 143],
       [172, 140, 177, 179],
       [160, 174, 159, 116],
       [121, 116, 214, 152],
       [196, 168, 149, 185],
       [208, 103, 239, 162],
       [243, 111, 241, 168],
       [221, 195, 135, 195],
       [226, 135, 146, 148],
       [162, 218, 175, 216],
       [178, 155, 241, 221],
       [163, 114, 124, 246],
       [198, 119, 104, 121],
       [131, 249, 140, 225],
       [109, 105, 108, 170],
       [183, 239, 247, 139],
       [200, 242, 103, 149],
       [248, 142, 139, 247],
       [220, 239, 150, 149],
       [117, 200, 227, 107],
       [233, 155, 176, 187],
       [120, 186, 158, 156],
       [207, 240, 160, 181],
       [216, 242, 157, 159],
       [232, 237, 142, 225],
       [165, 2

In [49]:
# На основі нового набору

# 3. Розрахувати сумарну, максимальну та мінімальну тривалості дзвінків для
# кожного місяця і середню кількість дзвінків по кожному місту.
np.sum(AllRegions,axis = 0)

array([7604, 7572, 6786, 7600])

In [51]:
np.max(AllRegions,axis = 0)

array([248, 249, 247, 247])

In [52]:
np.min(AllRegions,axis = 0)

array([105, 100, 100, 107])

In [53]:
np.average(AllRegions, axis = 1)

array([134.  , 139.25, 150.5 , 174.5 , 124.  , 139.25, 134.5 , 162.5 ,
       152.  , 129.  , 167.  , 152.25, 150.75, 174.5 , 178.  , 190.75,
       186.5 , 163.75, 192.75, 198.75, 161.75, 135.5 , 186.25, 123.  ,
       202.  , 173.5 , 194.  , 189.5 , 162.75, 187.75, 155.  , 197.  ,
       193.5 , 209.  , 191.75, 179.  , 171.5 , 131.5 , 166.  , 189.5 ,
       146.75, 186.75, 163.25, 199.5 ])

In [54]:
# 4. Розрахувати загальну (сумарну) тривалість дзвінків за три останніх місяці
# зазначеного в таблиці Б.3 діапазону по всьому набору даних.

np.sum(AllRegions[:,-3:], axis = 0)

array([7572, 6786, 7600])

In [32]:
# 5. Припустимо, що ви отримали 10 окремих рядків, які зберігають інформацію по 10 новим містам 
# за всі місяці 2017 року і минулі місяці 2018 (січень - жовтень) - 22 значення в кожному отриманому рядку.

NewData = np.random.randint(pMin,oMax, size = [10,22] )
NewData

array([[205, 146, 102, 146, 200, 244, 153, 132, 202, 162, 162, 173, 229,
        182, 159, 231, 172, 158, 107, 237, 116, 134],
       [184, 171, 166, 172, 120, 125, 187, 225, 181, 187, 228, 102, 247,
        226, 157, 164, 202, 174, 152, 156, 178, 188],
       [174, 180, 220, 234, 197, 129, 108, 188, 171, 166, 148, 201, 176,
        104, 166, 246, 178, 135, 206, 132, 242, 183],
       [201, 105, 231, 171, 130, 131, 238, 211, 113, 232, 178, 200, 122,
        188, 191, 176, 112, 135, 182, 200, 223, 104],
       [126, 103, 126, 228, 181, 237, 204, 161, 142, 201, 206, 189, 180,
        237, 106, 135, 248, 191, 108, 193, 196, 177],
       [130, 247, 123, 217, 237, 131, 242, 127, 233, 160, 149, 139, 135,
        235, 129, 181, 226, 244, 170, 245, 115, 139],
       [170, 246, 216, 172, 120, 196, 232, 246, 238, 114, 162, 210, 151,
        126, 166, 249, 201, 243, 237, 113, 102, 110],
       [121, 136, 230, 150, 120, 109, 124, 114, 123, 188, 223, 105, 190,
        140, 216, 208, 240, 140, 200, 

In [55]:
#6. Додайте нову інформацію в набір, вибравши інформацію тільки за ті місяці,
#які вам необхідні (таблиця Б.3)

NewAllRegions = np.vstack((NewData[:,6:10],AllRegions))
NewAllRegions

array([[153, 132, 202, 162],
       [187, 225, 181, 187],
       [108, 188, 171, 166],
       [238, 211, 113, 232],
       [204, 161, 142, 201],
       [242, 127, 233, 160],
       [232, 246, 238, 114],
       [124, 114, 123, 188],
       [199, 220, 191, 237],
       [162, 156, 163, 124],
       [105, 165, 129, 137],
       [113, 100, 166, 178],
       [135, 151, 150, 166],
       [172, 171, 176, 179],
       [134, 110, 120, 132],
       [158, 112, 148, 139],
       [125, 174, 105, 134],
       [176, 177, 129, 168],
       [176, 143, 179, 110],
       [119, 153, 101, 143],
       [172, 140, 177, 179],
       [160, 174, 159, 116],
       [121, 116, 214, 152],
       [196, 168, 149, 185],
       [208, 103, 239, 162],
       [243, 111, 241, 168],
       [221, 195, 135, 195],
       [226, 135, 146, 148],
       [162, 218, 175, 216],
       [178, 155, 241, 221],
       [163, 114, 124, 246],
       [198, 119, 104, 121],
       [131, 249, 140, 225],
       [109, 105, 108, 170],
       [183, 2

In [63]:
# 7. Використовуючи універсальні функції, вивести максимальну та мінімальну
# тривалості дзвінків по кожному місту і місяць (визначити назву міста та
# місяця за номером), коли вона була отримана.

np.argmax(NewAllRegions, axis = 1)

array([2, 1, 1, 0, 0, 0, 1, 3, 3, 2, 1, 3, 3, 3, 0, 0, 1, 1, 2, 1, 3, 1,
       2, 0, 2, 0, 0, 0, 1, 2, 3, 0, 1, 3, 2, 1, 0, 1, 2, 0, 1, 1, 1, 1,
       1, 3, 3, 3, 0, 1, 1, 0, 1, 1], dtype=int64)

In [64]:
np.max(NewAllRegions, axis = 1)

array([202, 225, 188, 238, 204, 242, 246, 188, 237, 163, 165, 178, 166,
       179, 134, 158, 174, 177, 179, 153, 179, 174, 214, 196, 239, 243,
       221, 226, 218, 241, 246, 198, 249, 170, 247, 242, 248, 239, 227,
       233, 186, 240, 242, 237, 222, 247, 215, 183, 191, 241, 166, 247,
       230, 247])

In [65]:
np.argmin(NewAllRegions, axis = 1)

array([1, 2, 0, 2, 2, 1, 3, 1, 2, 3, 0, 1, 0, 1, 1, 1, 2, 2, 3, 2, 1, 3,
       1, 2, 1, 1, 2, 1, 0, 1, 1, 2, 0, 1, 3, 2, 2, 3, 3, 1, 0, 2, 2, 2,
       0, 0, 2, 0, 1, 2, 3, 2, 2, 2], dtype=int64)

In [66]:
np.min(NewAllRegions, axis = 1)

array([132, 181, 108, 113, 142, 127, 114, 114, 191, 124, 105, 100, 135,
       171, 110, 112, 105, 129, 110, 101, 140, 116, 116, 149, 103, 111,
       135, 135, 162, 155, 114, 104, 131, 105, 139, 103, 139, 149, 107,
       155, 120, 160, 157, 142, 165, 140, 103, 109, 148, 148, 134, 116,
       100, 108])

In [74]:
# 8. За кожний місяць сформувати твердження: «В середньому в місяці Х
# тривалість дзвінків в роумінгу становила Y плюс \ мінус Z хвилин». Y і Z
# визначити за допомогою відповідних універсальних функцій. Х - номер
# місяця (від 1 до 12), а не номер стовпчика.
for i in range(0,4):
    print('В середньому, в місяці ', (i+6) ,' тривалість дзвінків у роумінгу становила ', np.average(NewAllRegions,axis=0)[i], ' плюс\мінус ', np.std(NewAllRegions[:,i]) )

В середньому, в місяці  6  тривалість дзвінків у роумінгу становила  175.05555555555554  плюс\мінус  43.16309151504098
В середньому, в місяці  7  тривалість дзвінків у роумінгу становила  173.1851851851852  плюс\мінус  46.79865227327958
В середньому, в місяці  8  тривалість дзвінків у роумінгу становила  158.2037037037037  плюс\мінус  41.190334909858194
В середньому, в місяці  9  тривалість дзвінків у роумінгу становила  173.53703703703704  плюс\мінус  37.41247215438097


In [76]:
# 9. Для кожного міста та місяця визначити і вивести таке значення тривалості
# дзвінків L, що все значення тривалості дзвінків для даного міста (місяця)
# менше L з ймовірністю 60%.

np.percentile(NewAllRegions, 60, axis=0)

array([187.8, 179.4, 162.4, 180.6])

In [77]:
np.percentile(NewAllRegions, 60, axis=1)

array([160.2, 187. , 170. , 227.8, 193. , 218.4, 236.8, 123.8, 215.8,
       160.8, 135.4, 155.4, 150.8, 175.2, 129.6, 146.2, 132.2, 174.4,
       169.4, 138.2, 176. , 159.8, 145.8, 181.6, 198.8, 226.4, 195. ,
       147.6, 207.8, 212.4, 155.2, 120.6, 208. , 108.8, 227.8, 189.8,
       226. , 206. , 183.4, 184.8, 157.6, 201.8, 204.6, 230.6, 201.4,
       175. , 186.4, 117.6, 171.2, 202.2, 148. , 192.6, 162.4, 228.4])