In [2]:
#Варіант №12
import numpy as np
#1. Файл “ratings.csv” зберігає інформацію про клієнтів online-бібліотеки,
#книги та оцінки книг читачами: book_id, user_id, rating.
#2. Прочитати з файлу відповідну частину стовбця user_id (діапазон строк
#задається по варіанту студента, див. Додаток А) у NumPy масив C_id.

#початок діапазону за варіантом - 121
#кінеці діапазону за варіантом - 24321
endpos = 24321-121+1
C_id = np.genfromtxt(fname = 'C:\\ratings.csv', delimiter=',' , skip_header=120, usecols=1,max_rows=endpos,dtype="int32")
C_id

array([11285, 11408, 11691, ...,  6054,  7563,  7976])

In [3]:
#3. Виконати генерацію значень NumPy масиву (CRT – Customer Reading
#Time), який зберігає інформацію про кількість хвилин, які витратили
#клієнти на читання книг, знаходячись безпосередньо на сайті в режимі 
#онлайн (за кожен з N1 останніх місяців поточного року у діапазоні від M1
#до M2). Значення N1, M1, M2 задаються відповідно варіанту студента
#(Додаток А).
N1 = 5 #місяців
M1 = 401 #мінімальна кільцість хвилин для генерації
M2 = 685 #максимальна кількість хвилин

CRT = np.random.randint(M1,M2,(len(C_id),N1))
CRT

array([[456, 652, 581, 423, 416],
       [432, 612, 632, 604, 621],
       [434, 603, 501, 452, 567],
       ...,
       [476, 680, 555, 655, 598],
       [564, 420, 618, 609, 487],
       [601, 409, 514, 677, 446]])

In [4]:
#4. Вивести інформацію щодо кількості хвилин, які витратили клієнти на
#читання книг у парні місяці (для парних варіантів студентів) або у непарні
#(для непарних варіантів студентів).
CRT[::,1::2]

array([[652, 423],
       [612, 604],
       [603, 452],
       ...,
       [680, 655],
       [420, 609],
       [409, 677]])

In [5]:
#5. Вивести інформацію по першим N2 (Додаток А) та останнім N3 клієнтам
#набору. N3 згенерувати використовуючи відповідну функцію модулю
#random.
N2 = 10943
N3 = np.random.randint(N2,len(CRT))
N3

17748

In [6]:
# Перші 10943 людини 
CRT[:N2,::]

array([[456, 652, 581, 423, 416],
       [432, 612, 632, 604, 621],
       [434, 603, 501, 452, 567],
       ...,
       [519, 612, 455, 470, 490],
       [635, 508, 460, 486, 592],
       [542, 621, 464, 408, 421]])

In [7]:
#останні N3 людини
CRT[len(CRT):N3:-1]

array([[601, 409, 514, 677, 446],
       [564, 420, 618, 609, 487],
       [476, 680, 555, 655, 598],
       ...,
       [406, 555, 420, 673, 430],
       [500, 506, 595, 516, 569],
       [491, 581, 492, 600, 637]])

In [8]:
#6. Вивести інформацію за перші три місяці для клієнта, user_id якого
#знаходиться в позиції N4 у C_id.
N4 = 8
CRT[C_id[N4],0:3]

array([424, 616, 484])

In [9]:
#7. Використовуючи логічну індексацію вивести інформацію для клієнта з
#відповідним user_id (user_id якого знаходиться в позиції N5 у C_id)
N5 = 226
CRT[C_id[N5]]

array([428, 474, 426, 422, 615])

In [10]:
#8. Для даного читача вивести інформацію за останні 2 місяця.
CRT[C_id[N5],-1:-3:-1]

array([615, 422])

In [11]:
#9. Використовуючи логічну індексацію вивести інформацію для клієнтів з
#user_id, відмінних від тих, що в позиціях N6, N7 у C_id.
N6 = 392
N7 = 27
print(C_id[N6], ' ; ', C_id[N7])

9246  ;  21217


In [12]:
selected = CRT[(C_id != C_id[N6])& (C_id != C_id[N7])]
selected

array([[456, 652, 581, 423, 416],
       [432, 612, 632, 604, 621],
       [434, 603, 501, 452, 567],
       ...,
       [476, 680, 555, 655, 598],
       [564, 420, 618, 609, 487],
       [601, 409, 514, 677, 446]])

In [13]:
#10.Для даних читачів вивести всі дані, про кількість хвилин, які витратили
#клієнти на читання книг, знаходячись безпосередньо на сайті в режимі
#онлайн більше ніж M3.
M3 = 446
selected[selected > M3]

array([456, 652, 581, ..., 601, 514, 677])

In [14]:
target = CRT[(C_id != C_id[N6])& (C_id != C_id[N7])]
target[target > M3]

array([456, 652, 581, ..., 601, 514, 677])

In [52]:
#11.Прочитати з файлу частину стовбця book_id відповідно до частини user_id,
#сформувати NumPy масив В_id. Для кожної книги з В_id на основі даних з
#CRT розрахувати загальну кількість хвилин, яку на неї витратили клієнти у
#першому місяці.
B_id = np.genfromtxt(fname = 'C:\\ratings.csv', delimiter=',' , skip_header=120, usecols=0,max_rows=endpos,dtype="int32")
books = np.unique(B_id)
time_spent = np.full(len(books),0)
for i in range(len(books)):
    time_spent[i] = np.sum(CRT[(B_id == books[i]),0])
time_spent

array([43682, 53864, 53060, 54846, 55515, 52773, 54009, 54660, 55372,
       53956, 55257, 53850, 54877, 55052, 55698, 54957, 53533, 53608,
       53895, 55173, 55527, 54584, 53533, 53963, 53909, 54346, 54644,
       54429, 53414, 53821, 53573, 53874, 54228, 54274, 53402, 54657,
       54224, 55031, 54376, 52847, 55642, 53366, 53666, 53727, 54636,
       53913, 54209, 54303, 54754, 55780, 53826, 54989, 53810, 52098,
       53537, 54120, 54825, 53742, 54207, 54473, 55164, 53330, 54828,
       54734, 55397, 54632, 56424, 54228, 54011, 54301, 53938, 54941,
       53502, 55439, 53822, 53609, 53849, 54703, 54490, 53761, 54687,
       54089, 52829, 55434, 55136, 55134, 53890, 53458, 53003, 55283,
       53806, 53554, 55326, 53495, 52777, 53822, 53711, 53927, 54131,
       53103, 53617, 54017, 54563, 53057, 53706, 54621, 53352, 54049,
       53554, 55819, 54311, 54174, 54612, 53955, 55126, 54121, 54289,
       52776, 54596, 54886, 54548, 54975, 54424, 54537, 53919, 52450,
       55231, 55638,

In [53]:
#12.Вивести загальну кількість хвилин, що було затрачено на читання книги
#всіма клієнтами з порядковим номером N8 (N8= No варіанту*5+No варіанту)
#у масиві В_id.
N8 = 12*5+12
np.sum(CRT[(B_id == N8)])

269090