In [1]:
import numpy as np

In [38]:
# Дані (video_games_sales.csv) зберігають інформацію про продажі відеоігор.
# Необхідно отримати інформацію (2-ма частинами, в масиви NumPy: 1
# частина - 1000 перших рядків, 2 частина - рядки файлу, що залишились) щодо
# продажів у різних регіонах: NA_Sales, EU_Sales, JP_Sales, Other_Sales, та про
# оцінку критиків «Critic_Score» (сформувати масиви games1 , games2)
# Також необхідно отримати інформацію про ігрові платформи Game
# Platform (game_names1, game_names2)
games1 = np.genfromtxt(fname = 'C:\\game_sales.csv', delimiter = ',', skip_header=1, usecols=(5,6,7,8,10), max_rows=1000,missing_values={"N/A"," "},filling_values=0.0)
games1

array([[4.136e+01, 2.896e+01, 3.770e+00, 8.450e+00, 7.600e+01],
       [1.568e+01, 1.276e+01, 3.790e+00, 3.290e+00, 8.200e+01],
       [1.561e+01, 1.093e+01, 3.280e+00, 2.950e+00, 8.000e+01],
       ...,
       [1.230e+00, 4.600e-01, 0.000e+00, 7.000e-02, 8.400e+01],
       [8.600e-01, 6.700e-01, 0.000e+00, 2.200e-01, 7.100e+01],
       [1.260e+00, 4.700e-01, 0.000e+00, 3.000e-02, 0.000e+00]])

In [39]:
games2 = np.genfromtxt(fname = 'C:\\game_sales.csv', delimiter = ',', skip_header=1001, usecols=(5,6,7,8,10),missing_values={"N/A"," "},filling_values=0.0)
games2

array([[5.20e-01, 9.50e-01, 0.00e+00, 2.90e-01, 7.00e+01],
       [6.10e-01, 8.70e-01, 2.00e-02, 2.60e-01, 8.40e+01],
       [1.68e+00, 4.00e-02, 0.00e+00, 4.00e-02, 0.00e+00],
       ...,
       [3.50e-01, 3.00e-02, 0.00e+00, 1.13e+00, 6.80e+01],
       [1.18e+00, 2.70e-01, 0.00e+00, 5.00e-02, 0.00e+00],
       [5.60e-01, 7.70e-01, 0.00e+00, 1.70e-01, 6.90e+01]])

In [32]:
game_names1 = np.genfromtxt(fname = 'C:\\game_sales.csv', delimiter = ',', skip_header=1, usecols = 1, dtype='unicode', max_rows=1000)
game_names1

array(['Wii', 'Wii', 'Wii', 'GB', 'GB', 'DS', 'Wii', 'Wii', 'NES', 'DS',
       'DS', 'GB', 'Wii', 'X360', 'Wii', 'PS3', 'PS2', 'SNES', 'DS', 'DS',
       'GB', 'NES', 'X360', 'PS2', 'GBA', 'DS', 'DS', 'PS2', 'X360', 'GB',
       'PS4', 'X360', '3DS', 'PS3', 'X360', 'X360', 'PS3', 'PS2', 'Wii',
       '3DS', 'PS3', 'PS4', 'DS', 'X360', 'N64', 'DS', '3DS', 'PS2',
       'Wii', 'GB', 'X360', 'PS', '3DS', 'PS3', 'PS3', 'SNES', 'PS3',
       'GBA', 'DS', 'X360', 'Wii', '3DS', 'N64', 'X360', 'PS', 'X360',
       'PS', 'Wii', 'PS3', 'X360', 'SNES', 'X360', '3DS', 'DS', 'X360',
       'SNES', 'PS4', 'XB', 'Wii', 'Wii', 'PS3', 'N64', 'DS', 'PS2', 'PC',
       'Wii', 'PS4', 'PS', '2600', 'DS', 'PSP', 'PS4', 'N64', 'PS4', 'PS',
       '3DS', 'Wii', 'NES', 'XOne', 'X360', 'X360', 'PS2', 'Wii', 'PS3',
       'PS4', 'PS', 'Wii', '3DS', 'PS', 'WiiU', 'GC', 'GC', 'PS2', 'PS2',
       'PS', 'Wii', 'X360', 'PS3', 'Wii', 'PS3', 'PS3', 'PS3', 'DS',
       'NES', 'PS3', 'PS3', 'PS3', 'Wii', 'XB', 'PS3', '

In [33]:
game_names2 = np.genfromtxt(fname = 'C:\\game_sales.csv', delimiter = ',', skip_header=1001, usecols = 1, dtype='unicode')
game_names2

array(['PS2', 'PS2', 'PS', 'XB', 'PS2', 'PS4', 'PS3', 'SNES', 'NES',
       'NES', 'PS4', 'PS3', 'X360', 'WiiU', 'PS2', 'GBA', 'PS3', 'PS',
       'PS2', 'PS3', 'X360', 'PS3', 'N64', 'PS', 'PS4', 'PS2', 'PS4',
       'PS', 'GB', 'DS', 'GBA', 'X360', 'PS2', 'PS4', 'PS2', 'XOne', 'XB',
       'PS2', 'PC', 'X360', 'PS', 'Wii', 'PS2', 'XB', 'DS', 'GBA', 'DS',
       'X360', 'DS', 'PS2', 'PS3', 'SNES', 'PS2', 'PC', 'PS4', 'DS',
       'Wii', 'PS2', 'PS3', 'PS', 'PS3', 'N64', 'PS', 'GBA', 'GBA', 'DS',
       'GC', 'DS', 'Wii', 'X360', 'PS2', 'PS', 'Wii', 'PS3', 'GB', 'PS',
       'PC', '3DS', 'PC', 'GBA', 'Wii', 'PSP', 'PS2', 'PS', 'XB', 'NES',
       'PS', 'XB', 'PS3', 'PS2', 'PS2', 'PS3', 'PC', 'PS2', 'PS4', 'Wii',
       'GEN', 'PS2', 'Wii', 'PS2', 'X360', 'PS2', 'X360', 'PS2', 'PS4',
       '2600', 'Wii', 'GC', 'SNES', 'Wii', 'X360', 'PS3', 'PS2', 'Wii',
       'GBA', 'X360', '2600', 'PS', 'NES', 'PS2', 'PS2', 'PS2', 'XOne',
       'XB', 'PS3', 'GC', 'PS2', 'X360', 'PC', 'PS', 'PS2', 'X3

In [42]:
games1[:,4] = games1[:,4].astype(int)
games1[:,4]

array([76., 82., 80.,  0.,  0., 89., 58., 87.,  0.,  0., 91.,  0., 80.,
       61., 80., 97., 95.,  0., 77.,  0.,  0.,  0., 97., 95.,  0., 77.,
        0., 95., 88.,  0.,  0., 87.,  0., 83., 83., 94., 88., 97., 93.,
       85., 88., 97., 86., 94.,  0.,  0.,  0., 89., 97.,  0., 98., 96.,
       90., 84., 94.,  0., 98.,  0.,  0., 73., 74., 78.,  0., 91., 92.,
       87., 93., 74., 71., 94.,  0.,  0., 88., 72., 96.,  0., 82., 95.,
       68., 62., 88.,  0.,  0., 92., 86.,  0.,  0., 90.,  0., 83., 88.,
       83.,  0., 85.,  0.,  0., 97.,  0.,  0., 84., 84., 85., 49., 85.,
       87., 96., 95.,  0., 91., 88., 92.,  0., 82., 88.,  0., 74., 93.,
       92.,  0., 94., 96.,  0., 74.,  0., 95., 86., 85., 87., 97., 92.,
       76., 85.,  0., 83., 95., 92.,  0., 93., 87., 91., 73., 94., 82.,
       96.,  0., 94., 94., 92., 95., 95., 89., 87., 89., 76., 80., 67.,
        0.,  0., 91., 81., 92., 84., 81., 96., 97., 93.,  0.,  0., 66.,
       85., 93.,  0., 83.,  0., 94., 84., 85.,  0., 81.,  0., 90

In [44]:
games2[:,4] = games2[:,4].astype(int)
games2[:,4]

array([70., 84.,  0., 80.,  0., 82., 83.,  0.,  0.,  0.,  0., 81., 83.,
       65., 55.,  0.,  0.,  0., 83.,  0., 55., 78.,  0.,  0., 63., 92.,
       54.,  0.,  0., 78., 78., 79.,  0., 61.,  0., 82., 91., 80., 78.,
       88.,  0., 89., 84., 83.,  0., 65.,  0.,  0., 20.,  0., 95.,  0.,
       87., 74., 71.,  0.,  0., 82., 94.,  0.,  0.,  0.,  0., 64., 53.,
        0., 96., 63., 37., 64.,  0.,  0., 78., 82.,  0.,  0., 90.,  0.,
       79., 92., 67., 73., 93., 90., 83.,  0., 87.,  0., 87., 84., 94.,
       83., 86., 71., 79., 44.,  0., 93., 78., 83., 81., 83., 79., 72.,
       89.,  0., 77., 71.,  0., 56., 77., 79.,  0., 68.,  0., 72.,  0.,
        0.,  0., 88.,  0., 83., 82., 92., 70., 89., 89.,  0., 81., 90.,
       88., 86., 84.,  0., 74., 61., 83.,  0.,  0., 92., 80., 77.,  0.,
        0., 76.,  0., 81., 69., 64.,  0.,  0.,  0., 81., 86., 72.,  0.,
       83., 94., 85., 96.,  0.,  0., 74.,  0., 53., 75., 69., 85.,  0.,
       76., 76., 66., 84., 78.,  0., 90., 79., 78., 72.,  0., 80

In [45]:
# 3. Вивести кількість унікальних назв Game Platform для кожної частини.
np.unique(game_names1)

array(['2600', '3DS', 'DC', 'DS', 'GB', 'GBA', 'GC', 'GEN', 'N64', 'NES',
       'PC', 'PS', 'PS2', 'PS3', 'PS4', 'PSP', 'PSV', 'SAT', 'SNES',
       'Wii', 'WiiU', 'X360', 'XB', 'XOne'], dtype='<U4')

In [46]:
np.unique(game_names2)

array(['2600', '3DS', 'DS', 'GB', 'GBA', 'GC', 'GEN', 'N64', 'NES', 'PC',
       'PS', 'PS2', 'PS3', 'PS4', 'PSP', 'PSV', 'SNES', 'Wii', 'WiiU',
       'X360', 'XB', 'XOne'], dtype='<U4')

In [47]:
# 4. Вивести загальні назви Game Platform для games1 і games2
np.intersect1d(game_names1, game_names2)

array(['2600', '3DS', 'DS', 'GB', 'GBA', 'GC', 'GEN', 'N64', 'NES', 'PC',
       'PS', 'PS2', 'PS3', 'PS4', 'PSP', 'PSV', 'SNES', 'Wii', 'WiiU',
       'X360', 'XB', 'XOne'], dtype='<U4')

In [48]:
# 5. Вивести різні (непересічні) назви Game Platform для games1 і games2
np.setxor1d(game_names1, game_names2)

array(['DC', 'SAT'], dtype='<U4')

In [50]:
# 6. Для першої частини ігор ціни (на гру) в регіонах North America Region,
# EU Region і Japan Region складають 100.5, 98.3, 124.4 y.о відповідно і 110.7, 99.6,
# 128.2 y.о для другої частини ігор.
g_price1 = np.array([100.5,98.3,124.4])
g_price2 = np.array([110.7, 99.6,128.2])

In [56]:
# 7. Використовуючи broadcasting і 2 np.arrays (для зберігання цін: g_price1,
# g_price2) створіть 2 np.arrays (games1_cost, games2_cost) для зберігання
# результатів обчислення вартості.
games1_cost=games1[:,0:3]
games1_cost = games1_cost * g_price1
games1_cost

array([[4156.68 , 2846.768,  468.988],
       [1575.84 , 1254.308,  471.476],
       [1568.805, 1074.419,  408.032],
       ...,
       [ 123.615,   45.218,    0.   ],
       [  86.43 ,   65.861,    0.   ],
       [ 126.63 ,   46.201,    0.   ]])

In [58]:
games2_cost=games2[:,0:3]
games2_cost = games2_cost * g_price2
games2_cost

array([[ 57.564,  94.62 ,   0.   ],
       [ 67.527,  86.652,   2.564],
       [185.976,   3.984,   0.   ],
       [137.268,  44.82 ,   0.   ],
       [  6.642,  89.64 ,  67.946],
       [138.375,  16.932,   0.   ],
       [ 49.815,  91.632,   7.692],
       [104.058,  33.864,  26.922],
       [ 87.453,  13.944, 102.56 ],
       [ 77.49 ,  12.948, 116.662],
       [ 74.169,  78.684,   0.   ],
       [ 38.745, 105.576,   2.564],
       [110.7  ,  52.788,   3.846],
       [ 33.21 ,  55.776, 107.688],
       [ 94.095,  65.736,   1.282],
       [138.375,  45.816,   0.   ],
       [ 99.63 ,  34.86 ,  32.05 ],
       [ 79.704,  88.644,   5.128],
       [ 69.741,  48.804,  57.69 ],
       [ 61.992,  80.676,  12.82 ],
       [116.235,  51.792,   3.846],
       [ 45.387,  43.824,  92.304],
       [187.083,   3.984,   0.   ],
       [183.762,   3.984,   0.   ],
       [ 67.527,  77.688,   7.692],
       [ 94.095,  65.736,   0.   ],
       [ 47.601,  67.728,  53.844],
       [163.836,  19.92 ,   

In [63]:
# 8. Виведіть кількість рядків (r1) в games1, де загальні NA, EU, JP продажу
# менше ніж Other_Sales. Порівняйте з відповідним значенням r2 для games2 та
# зробіть висновки.
r1 = 0
for i in range(len(games1)):
    if np.sum(games1[i,0:3]) < games1[i,3]:
        r1 = r1+1
r1

10

In [64]:
r2 = 0
for i in range(len(games2)):
    if np.sum(games2[i,0:3]) < games2[i,3]:
        r1 = r1+1
r1

14