In [1]:
import numpy as np

In [15]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [19]:
data = np.random.uniform(-1,1,28)
data = data.reshape(7,4)

In [21]:
data[names == 'Bob']

array([[-0.08497896, -0.6899556 , -0.51229056, -0.62442866],
       [-0.439867  , -0.11107857, -0.4047544 ,  0.6268036 ]])

In [22]:
data[data<0]= 0
data

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.61865917, 0.        , 0.        ],
       [0.        , 0.        , 0.79016631, 0.        ],
       [0.        , 0.        , 0.        , 0.6268036 ],
       [0.        , 0.18908792, 0.97906826, 0.        ],
       [0.47708882, 0.5806051 , 0.39326819, 0.        ],
       [0.59846501, 0.33255645, 0.        , 0.        ]])

In [23]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.61865917, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.47708882, 0.5806051 , 0.39326819, 0.        ],
       [0.59846501, 0.33255645, 0.        , 0.        ]])

In [24]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [26]:
data = np.random.uniform(-1,1,28)
data = data.reshape(7,4)
data[mask]

array([[-0.93206392, -0.81989344, -0.75704325, -0.65096005],
       [-0.33860518,  0.18492805, -0.65600421, -0.84295753],
       [ 0.14450507,  0.68283319, -0.68427743,  0.68849225],
       [ 0.9223003 , -0.89124151, -0.19747403,  0.33065834]])

In [27]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [29]:
data[~(names == 'Bob')]

array([[ 0.44963256, -0.78239884, -0.56632004,  0.33401048],
       [-0.33860518,  0.18492805, -0.65600421, -0.84295753],
       [ 0.9223003 , -0.89124151, -0.19747403,  0.33065834],
       [ 0.35278199, -0.30917753, -0.57739214, -0.68532886],
       [ 0.0902156 ,  0.73989465, -0.02718225, -0.39872025]])

In [30]:
data[names != 'Bob']

array([[ 0.44963256, -0.78239884, -0.56632004,  0.33401048],
       [-0.33860518,  0.18492805, -0.65600421, -0.84295753],
       [ 0.9223003 , -0.89124151, -0.19747403,  0.33065834],
       [ 0.35278199, -0.30917753, -0.57739214, -0.68532886],
       [ 0.0902156 ,  0.73989465, -0.02718225, -0.39872025]])

In [47]:
data_copy = data[:2,:2].copy()
data_copy

array([[-0.93206392, -0.81989344],
       [ 0.44963256, -0.78239884]])

In [48]:
data_copy[0,0] = 42
data_copy

array([[42.        , -0.81989344],
       [ 0.44963256, -0.78239884]])

In [49]:
data

array([[-0.93206392, -0.81989344, -0.75704325, -0.65096005],
       [ 0.44963256, -0.78239884, -0.56632004,  0.33401048],
       [-0.33860518,  0.18492805, -0.65600421, -0.84295753],
       [ 0.14450507,  0.68283319, -0.68427743,  0.68849225],
       [ 0.9223003 , -0.89124151, -0.19747403,  0.33065834],
       [ 0.35278199, -0.30917753, -0.57739214, -0.68532886],
       [ 0.0902156 ,  0.73989465, -0.02718225, -0.39872025]])

In [50]:
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
data[names == 'Bob']

array([[-0.93206392, -0.81989344, -0.75704325, -0.65096005],
       [ 0.14450507,  0.68283319, -0.68427743,  0.68849225]])

In [52]:
data[names == 'Bob', 2:]

array([[-0.75704325, -0.65096005],
       [-0.68427743,  0.68849225]])

In [53]:
data[names == 'Bob',3]

array([-0.65096005,  0.68849225])