In [1]:
import numpy as np

In [3]:
v = np.array([1,2,3,4,5,6])

In [4]:
v


array([1, 2, 3, 4, 5, 6])

In [5]:
data1 = [6,2.51,31,76,1]
arr1 = np.array(data1)

In [6]:
arr1

array([ 6.  ,  2.51, 31.  , 76.  ,  1.  ])

In [7]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [8]:
arr1.ndim

1

In [9]:
arr1.shape

(5,)

In [10]:
arr1.size

5

In [11]:
arr1.dtype

dtype('float64')

In [12]:
v.dtype

dtype('int32')

In [13]:
data2 = [[1,2,3],[4,5,6]]

In [14]:
arr2 = np.array(data2)

In [15]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.array([range(i,i+3) for i in[2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [20]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [23]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [25]:
np.linspace(0.0,2.0,4,retstep=True)

(array([0.        , 0.66666667, 1.33333333, 2.        ]), 0.6666666666666666)

In [26]:
t = np.arange(-1.0,1.0,0.2)

In [27]:
t

array([-1.00000000e+00, -8.00000000e-01, -6.00000000e-01, -4.00000000e-01,
       -2.00000000e-01, -2.22044605e-16,  2.00000000e-01,  4.00000000e-01,
        6.00000000e-01,  8.00000000e-01])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [31]:
a = np.array([[1,2,3],[4,5,6]])

In [32]:
b = a

In [33]:
a is b

True

In [34]:
b = a.copy()

In [35]:
b is a

False

In [36]:
arr1[0]

6.0

In [37]:
arr1[4]

1.0

In [38]:
arr1[-1]

1.0

In [39]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr2[1][1]

5

In [42]:
arr2[0][2]

3

In [43]:
arr2[0][2] = 33

In [44]:
arr2

array([[ 1,  2, 33],
       [ 4,  5,  6]])

In [45]:
arr = np.arange(10)

In [46]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr[5:8] = 12

In [48]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])