In [2]:
import numpy as np

In [3]:
#создать вектор нулевых значений длинной а
a = 15
v1 = np.zeros(a)
v1 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
#создать вектор нулевых значений длинной b, заменить b-4й элемент на с
b=12
c=8
v2 = np.zeros(b)
v2[b-4] = 8
v2

array([0., 0., 0., 0., 0., 0., 0., 0., 8., 0., 0., 0.])

In [5]:
#Создать вектор со значениями в диапазоне от n до m
m = 4
n = 9
v3 = np.arange(4,10)
v3

array([4, 5, 6, 7, 8, 9])

In [6]:
#Развернуть вектор (первый элемент становится последним)
v3_reversed = v3[::-1]
v3_reversed

array([9, 8, 7, 6, 5, 4])

In [7]:
#Со списка L=[0,1,2,3,4,5,6,7,8] создать матрицу 3х3.
L=np.array([0,1,2,3,4,5,6,7,8]).reshape(3,3)
L

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
#Создать матрицу 2x3 со значениями в диапазоне от 0 до 5
mat1 = np.arange(6).reshape(2,3)
mat1

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
#Создать матрицу a x b с 5 внутри, и 1 на границах
a1 = 4
b1 = 5
mat2 = np.ones((a1,b1), dtype = int)
mat2[1:-1,1:-1] = 5
mat2

array([[1, 1, 1, 1, 1],
       [1, 5, 5, 5, 1],
       [1, 5, 5, 5, 1],
       [1, 1, 1, 1, 1]])

In [10]:
#Сформировать срезы для получения элементов на красном фоне
arr1 = np.array([2,3,6,8,11,34])
arr1[2:4]

array([6, 8])

In [19]:
arr2 = np.array([[2,3,6,8,11,34],[11,22,3,67,11,87],[3,6,3,11,89,14],[4,5,8,1,4,67]])
arr2

array([[ 2,  3,  6,  8, 11, 34],
       [11, 22,  3, 67, 11, 87],
       [ 3,  6,  3, 11, 89, 14],
       [ 4,  5,  8,  1,  4, 67]])

In [18]:
arr3 = arr2[0:,[1,2]]
arr3

array([[ 3,  6],
       [22,  3],
       [ 6,  3],
       [ 5,  8]])

In [20]:
arr4 = arr2[0:,[1,3,5]]
arr4

array([[ 3,  8, 34],
       [22, 67, 87],
       [ 6, 11, 14],
       [ 5,  1, 67]])

In [21]:
arr6 = arr2[2,[0,1,2]]
arr6

array([3, 6, 3])

In [29]:
arr7 = arr2[1:4,[4,5]]
arr7

array([[11, 87],
       [89, 14],
       [ 4, 67]])