In [77]:
import numpy as np

In [78]:
min = 165
max = 33165
N1 = 8
N2 = 19846
N4 = 471
N5 = 280
N6 = 408
N7 = 188
N8 = 15*5+15
M1 = 764
M2 = 438
M3 = 748

In [79]:
OpenCode = np.genfromtxt('ratings.csv - ratings.csv', dtype=int, skip_header=1, max_rows=1000000, delimiter=',')
C_id = source[min:max,1]
C_id

array([32055, 32305, 32592, ..., 30283, 30513, 30944])

In [80]:
CRT = np.random.randint(M2, M1, size=[C_id.size,N1], dtype=int)
N3 = np.random.randint(CRT.shape[0])
CRT

array([[755, 596, 546, ..., 480, 739, 716],
       [443, 650, 683, ..., 639, 538, 583],
       [638, 653, 614, ..., 506, 716, 466],
       ...,
       [704, 742, 477, ..., 487, 679, 534],
       [548, 691, 656, ..., 623, 634, 712],
       [469, 603, 515, ..., 687, 754, 444]])

4. Вивести інформацію щодо кількості хвилин, які витратили клієнти на
читання книг у парні місяці (для парних варіантів студентів) або у непарні
(для непарних варіантів студентів).  

In [81]:
CRT[::,1::2]

array([[596, 472, 480, 716],
       [650, 454, 639, 583],
       [653, 490, 506, 466],
       ...,
       [742, 688, 487, 534],
       [691, 453, 623, 712],
       [603, 493, 687, 444]])

5. Вивести інформацію по першим N2(19846) (Додаток А) та останнім N3 клієнтам
набору. N3 згенерувати використовуючи відповідну функцію модулю
random.

In [82]:
CRT[:N2:]

array([[755, 596, 546, ..., 480, 739, 716],
       [443, 650, 683, ..., 639, 538, 583],
       [638, 653, 614, ..., 506, 716, 466],
       ...,
       [535, 500, 447, ..., 461, 680, 686],
       [700, 460, 741, ..., 566, 467, 558],
       [648, 655, 636, ..., 757, 673, 560]])

In [83]:
CRT[N3::]

array([[681, 673, 540, ..., 538, 740, 557],
       [723, 565, 440, ..., 585, 671, 481],
       [492, 514, 462, ..., 671, 675, 719],
       ...,
       [704, 742, 477, ..., 487, 679, 534],
       [548, 691, 656, ..., 623, 634, 712],
       [469, 603, 515, ..., 687, 754, 444]])

6. Вивести інформацію за перші три місяці для клієнта, user_id якого
знаходиться в позиції N4(471) у C_id.

Используем mask - массивоподобный объект NumPy. Булев массив того же размера, что и a , который является маской для исходного массива и определяет какие элементы должны быть заменены: True - замена выполняется, False - элемент остается без изменений.

In [84]:
mask = (C_id == C_id[N4])
CRT[mask,:3:]

array([[440, 456, 571],
       [597, 689, 475],
       [557, 674, 451],
       [736, 526, 747],
       [476, 557, 684],
       [710, 526, 676],
       [700, 717, 663],
       [448, 509, 681],
       [713, 502, 612],
       [541, 681, 730],
       [468, 602, 513],
       [723, 501, 729],
       [569, 693, 501],
       [657, 685, 753],
       [761, 682, 570],
       [711, 660, 641],
       [719, 747, 469],
       [702, 470, 674],
       [587, 639, 556],
       [531, 635, 747],
       [576, 619, 481],
       [695, 469, 544],
       [536, 740, 492],
       [489, 474, 746],
       [588, 568, 643],
       [496, 711, 603],
       [624, 707, 570],
       [676, 642, 658],
       [618, 751, 617],
       [669, 474, 688],
       [541, 549, 582],
       [634, 748, 700],
       [639, 690, 559],
       [656, 506, 552],
       [748, 451, 565],
       [473, 574, 755],
       [568, 660, 750],
       [493, 494, 708],
       [491, 758, 477],
       [577, 694, 594],
       [469, 544, 719],
       [677, 763

7. Використовуючи логічну індексацію вивести інформацію для клієнта з
відповідним user_id (user_id якого знаходиться в позиції N5(280) у C_id)

In [85]:
mask = (C_id == C_id[N5])
uniqUser = CRT[mask]
uniqUser

array([[705, 659, 552, 565, 510, 512, 547, 518],
       [554, 516, 581, 514, 591, 549, 607, 546],
       [574, 491, 587, 585, 640, 661, 537, 565],
       [635, 735, 717, 608, 466, 451, 502, 459],
       [478, 543, 625, 568, 531, 744, 663, 507],
       [748, 584, 605, 725, 677, 687, 585, 635],
       [592, 723, 747, 453, 652, 527, 573, 649],
       [512, 750, 541, 566, 740, 508, 640, 445],
       [681, 634, 440, 485, 571, 444, 452, 732],
       [563, 633, 592, 637, 708, 700, 606, 609],
       [654, 586, 708, 502, 735, 542, 553, 736],
       [732, 536, 491, 489, 457, 753, 476, 463],
       [761, 554, 563, 611, 535, 747, 542, 681],
       [722, 567, 710, 452, 739, 578, 707, 643],
       [525, 698, 570, 618, 506, 622, 472, 677],
       [647, 497, 671, 611, 751, 545, 451, 660],
       [442, 489, 610, 723, 565, 572, 677, 622],
       [531, 652, 630, 761, 693, 481, 569, 752],
       [552, 686, 632, 714, 564, 744, 723, 566],
       [757, 498, 724, 565, 543, 714, 700, 614],
       [627, 598, 67

8. Для даного читача вивести інформацію за останні 2 місяця.

In [86]:
uniqUser[:,-2:]

array([[547, 518],
       [607, 546],
       [537, 565],
       [502, 459],
       [663, 507],
       [585, 635],
       [573, 649],
       [640, 445],
       [452, 732],
       [606, 609],
       [553, 736],
       [476, 463],
       [542, 681],
       [707, 643],
       [472, 677],
       [451, 660],
       [677, 622],
       [569, 752],
       [723, 566],
       [700, 614],
       [626, 447],
       [464, 660],
       [668, 640],
       [756, 550],
       [508, 474],
       [606, 752],
       [686, 620],
       [607, 595],
       [490, 586],
       [447, 584],
       [594, 574],
       [693, 708],
       [605, 554],
       [733, 755],
       [508, 713],
       [714, 576],
       [538, 564],
       [548, 512],
       [695, 679],
       [599, 663],
       [638, 598],
       [688, 637],
       [533, 636],
       [741, 603],
       [528, 692],
       [705, 581],
       [480, 525],
       [762, 649],
       [658, 747],
       [721, 508],
       [438, 595],
       [744, 659],
       [512,

9. Використовуючи логічну індексацію вивести інформацію для клієнтів з
user_id, відмінних від тих, що в позиціях N6 (408)
N7 (188) у C_id.

In [87]:
mask = (C_id == C_id[N6]) | (C_id == C_id[N7])

In [88]:
uniqUsers = CRT[~mask]
uniqUsers

array([[755, 596, 546, ..., 480, 739, 716],
       [443, 650, 683, ..., 639, 538, 583],
       [638, 653, 614, ..., 506, 716, 466],
       ...,
       [704, 742, 477, ..., 487, 679, 534],
       [548, 691, 656, ..., 623, 634, 712],
       [469, 603, 515, ..., 687, 754, 444]])

10.Для даних читачів вивести всі дані, де про кількість хвилин, які витратили
клієнти на читання книг, знаходячись безпосередньо на сайті в режимі
онлайн більше ніж M3 (748).

In [89]:
uniqUsers[uniqUsers > M3]

array([755, 750, 753, ..., 758, 759, 754])

11.Прочитати з файлу частину стовбця book_id відповідно до частини user_id,
сформувати NumPy масив В_id. Для кожної книги з В_id на основі даних з
CRT розрахувати загальну кількість хвилин, яку на неї витратили клієнти у
першому місяці.

In [90]:
B_id = source[min:max,0]
B_id

array([  2,   2,   2, ..., 332, 332, 332])

In [91]:
mask = (C_id == C_id[N4])
np.sum(CRT[mask,1], axis=0)

43114

12.Вивести загальну кількість хвилин, що було затрачено на читання книги
всіма клієнтами з порядковим номером N8 (N8= No варіанту*5+No варіанту) (15*5+15)
у масиві В_id.

In [92]:
mask = (B_id == B_id[N8])
np.sum(CRT[mask])

480692